
services:
  secure-app:
    build: .
    container_name: phase-2-secure-app
    ports:
      - "5000:5000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
    restart: unless-stopped


